# Generated by Django 4.1.3 on 2022-12-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.TextField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
