# Generated by Django 4.1.3 on 2022-12-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_organization_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
