# Generated by Django 4.1.3 on 2022-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tittle',
            field=models.CharField(max_length=50, verbose_name='Краткое название'),
        ),
    ]
