# Generated by Django 4.1.3 on 2022-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_organization_tittle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('product_name', models.CharField(max_length=5, verbose_name='Краткое название')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание товара')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Информация о товарах',
            },
        ),
    ]
