# Generated by Django 4.1.3 on 2022-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_catalog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('news_image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('news_description', models.TextField(verbose_name='Описание новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Информация о новости',
            },
        ),
    ]
